project: koden
source:
  repoURL: https://charts.bitnami.com/bitnami
  targetRevision: 13.6.5
  helm:
    valueFiles:
      - >-
        https://raw.githubusercontent.com/koden-process/koden-mongodb-k8s/refs/heads/main/values.yaml
    values: |
      auth:
        existingSecret: mongodb-koden-meow-secret
        usernames:
          - admin
        databases:
          - meow
  chart: mongodb
destination:
  server: https://kubernetes.default.svc
  namespace: koden
syncPolicy:
  automated:
    prune: true
    selfHeal: true
